---
title: "benchmark"
author: "Mike Jiang"
date: "May 25, 2017"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r, echo=FALSE}
library(microbenchmark)
library(Matrix)
library(data.table)
# library(RSQLite)
library(rhdf5)
library(singleCell)
library(ggplot2)
library(TENxGenomics)
library(HDF5Array)
Sys.setenv(HDF5_PLUGIN_PATH="/home/wjiang2/mylib/lib")
path <- "/loc/no-backup/mike/shared"
path <- file.path(path, "1M_neurons")
tenxFile <-  file.path(path, "1M_neurons_filtered_gene_bc_matrices_h5.h5")
ten <- TENxGenomics(tenxFile)
ten <- ten[1:1e3, 1:1e4]
dims <- dim(ten)
nGenes <- dims[1]
nCells <- dims[2]
h5gz1 <- file.path(path, "gz_chunk_by_cell.h5")
h5gz <- file.path(path, "gz.h5")
h5lz <- file.path(path, "lz.h5")

```

```{r, eval=FALSE, echo=FALSE, results= "hide"}
#convert to 2d sparse mat

#write h5 gene x cell
block.size <- 100
H5write.blocks(ten, h5gz1, ncol = nCells, nrow = nGenes, compress = "gzip", block.size = block.size, verbose = T)
#transpose it
h5array <- t(HDF5Array(h5gz1, "data"))
#write h5 as cell x gene
block.size <- 10
H5write.blocks(h5array, h5gz, ncol = nGenes, nrow = nCells, compress = "gzip", block.size = block.size,verbose = T)
#convert it to lz format
h5array <- HDF5Array(h5gz, "data")
H5write.blocks(h5array, h5lz, ncol = nGenes, nrow = nCells, compress = "lz4", block.size = block.size, verbose = T)

```

```{r}
file.size(tenxFile) /1e9
file.size(h5gz) /1e9
file.size(h5lz) /1e9
```

## benchmark different formats
```{r, echo=FALSE}
h5array <- HDF5Array(h5gz, "data")
set.seed(4)
nGeneSampleSizeVec <- c(1e3, 3e3, 5e3, 1e4)
nCellSampleSizeVec <- c(1e3, 3e3, 5e3, 1e4)

ntime <- 5
# Rprof()

benchmarkfile <- file.path(path,paste0("dt_", paste(nGenes, sep = "_"), ".rds"))
if(!file.exists(benchmarkfile))
{
   res <- lapply(nGeneSampleSizeVec, function(nGeneSampleSize){
              cidx <- sample(nGenes, nGeneSampleSize)
              
              res <- lapply(nCellSampleSizeVec, function(nCellSampleSize){
                
                ridx <- sample(nCells, nCellSampleSize)
                
                #CSC TENx
                  # browser()
                # sparsity <- 1- nnzero(ten)/(nCells * nGenes)
                
                # timing <- microbenchmark(dd <- as.matrix(ten[ridx, ])
                #                          , dd <- as.matrix(ten[, cidx])
                #                          , sub1 <- as.matrix(ten[ridx, cidx])
                #                          , times = ntime, unit = "ms")
                # timing <- summary(timing)[["mean"]]
                # dt1 <- data.table(format = "CSC"
                #                   , slicing = c("row", "col", "row&col")
                #                   , time = timing)
                
               # browser()
               #H5array
               
               

               timing <- microbenchmark(dd <- as.matrix(h5array[ridx, ])
                                         ,dd <-  as.matrix(h5array[, cidx])
                                         , sub2 <- as.matrix(h5array[ridx, cidx])
                                         , times = ntime, unit = "ms")
               timing <- summary(timing)[["mean"]]
               dt2 <- data.table(format = "h5array (gzip)"
                                  , slicing = c("row", "col", "row&col")
                                  , time = timing)  


               
                #chunked.read.h5 gzip
                timing <- microbenchmark(dd <- h5read.chunked(h5gz, "data", list(ridx, NULL), nGenes, block.size = block.size)
                                         ,dd <-  h5read.chunked(h5gz, "data", list(NULL, cidx), nGenes, block.size = block.size)
                                         , sub3 <- h5read.chunked(h5gz, "data", list(ridx, cidx), nGenes, block.size = block.size)
                                         , times = ntime, unit = "ms")
                
                
                # H5close()
                compress <- "gzip"
                timing <- summary(timing)[["mean"]]
                dt3 <- data.table(format = paste0("H5(chunked.read)", compress)
                                  , slicing = c("row", "col", "row&col")
                                  , time = timing)
                
                #chunked.read.h5 gzip
                compress <- "lz4"
                timing <- microbenchmark(dd <- h5read.chunked(h5lz, "data", list(ridx, NULL), nGenes, block.size = block.size)
                                         ,dd <-  h5read.chunked(h5lz, "data", list(NULL, cidx), nGenes, block.size = block.size)
                                         , sub4 <- h5read.chunked(h5lz, "data", list(ridx, cidx), nGenes, block.size = block.size)
                                         , times = ntime, unit = "ms")
                
                
                H5close()
                
                timing <- summary(timing)[["mean"]]
                dt4 <- data.table(format = paste0("H5(chunked.read)", compress)
                                  , slicing = c("row", "col", "row&col")
                                  , time = timing)
                # browser()
                
                
                if(!isTRUE(all.equal(sub2, sub3, check.attributes = F, tol = 2e-8))||!isTRUE(all.equal(sub2, sub4, check.attributes = F, tol = 2e-8)))
                  stop("wrong reading!")
                thisRes <- rbindlist(list(dt2, dt3, dt4))
                thisRes[, nGenes := nGeneSampleSize]
                thisRes[, nCells := nCellSampleSize]
                
                                  
              })
              rbindlist(res)
            })
  # Rprof(NULL)
  # summaryRprof()
  dt <- rbindlist(res)
  saveRDS(dt, file = benchmarkfile)
}else
  dt <- readRDS(benchmarkfile)
```

## plot the result
```{r fig.width=14}
ggplot(dt, aes(y = time, x = slicing , fill = format)) + geom_col(position = "dodge") + facet_grid(nCells~nGenes, scales ="free") + ylab("time (ms)") + scale_y_log10()


```


