---
title: "benchmark"
author: "Mike Jiang"
date: "May 25, 2017"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r, echo=FALSE}
library(microbenchmark)
library(Matrix)
library(data.table)
# library(RSQLite)
library(rhdf5)
library(singleCell)
library(ggplot2)
library(TENxGenomics)
library(HDF5Array)
Sys.setenv(HDF5_PLUGIN_PATH="/home/wjiang2/rglab/workspace/h5lz/src/Release/")
path <- "/loc/no-backup/mike/shared"
path <- file.path(path, "1M_neurons")
tenxFile <-  file.path(path, "1M_neurons_filtered_gene_bc_matrices_h5.h5")
#data of the original size 1M cells
h5gz_gene <- file.path(path, "gz_chunk_by_gene.h5")
h5gz_cell <- file.path(path, "gz_chunk_by_cell.h5")
h5array_cell <- HDF5Array(h5gz_cell, "data")
h5array_gene <- HDF5Array(h5gz_gene, "data")
dims <- dim(h5array_gene)
dims
nGenes <- dims[2]
nCells <- dims[1]
```
```{r subset data}
h5lz_gene <- file.path(path, "lz_chunk_by_gene_sub.h5")
h5lz_cell <- file.path(path, "lz_chunk_by_cell_sub.h5")
h5gz_gene <- file.path(path, "gz_chunk_by_gene_sub.h5")
h5gz_cell <- file.path(path, "gz_chunk_by_cell_sub.h5")

#get 10k cells 
# gene.ind <- sample(nGenes, 2e3)
# cell.ind <- sample(nCells, 5e3)
#randm selection was too slow for h5array
# gene.ind <- 1:2e3
nCells <- 1e4
cell.ind <- seq_len(nCells)
h5array_cell <- h5array_cell[, cell.ind]
h5array_gene <- h5array_gene[cell.ind, ]

```



```{r write the subset to disk in different format, eval=FALSE, echo=FALSE}
system.time(H5write.blocks(h5array_cell, h5lz_cell, ncol = nCells , nrow = nGenes, compress = "lz4", block.size = 100, verbose = T)) #50s

system.time(H5write.blocks(h5array_cell, h5gz_gene, ncol = nCells , nrow = nGenes, compress = "gzip", block.size = 100, verbose = T)) #63.2s

#277s
system.time(H5write.blocks(h5array_gene, h5lz_gene,  nGenes, nCells , compress = "lz4", block.size = 100, verbose = T)) 
#286s
system.time(H5write.blocks(h5array_gene, h5gz_cell,  nGenes, nCells, compress = "gzip", block.size = 100, verbose = T)) 


#in-memory version
mat1 <- h5read.chunked(h5gz_cell, "data", list(NULL, NULL), nCells, mc.cores = 10)
mat <- Matrix(mat1, sparse = T)
saveRDS(mat, file = file.path(path, "mat.rds"))

```


```{r}
mat <- readRDS(file = file.path(path, "mat.rds"))
format(object.size(mat), unit = "MB")
file.size(h5gz_gene) /1e6
file.size(h5gz_cell) /1e6
file.size(h5lz_gene) /1e6
file.size(h5lz_cell) /1e6

# file.size(h5uncompress) /1e9
```

## benchmark different formats
```{r benchmark, echo=FALSE}
sc.gz <- singleCell(h5gz_gene, h5gz_cell)
sc.lz <- singleCell(h5lz_gene, h5lz_cell)
h5array_cell <- HDF5Array(h5gz_cell, "data")
h5array_gene <- HDF5Array(h5gz_gene, "data")
block.size <- 10

set.seed(4)
idx <- matrix(c( 10,10
                 ,100,100
                  ,1 , NA
                 , 10, NA
                 , 100 , NA
                 , 300 , NA
                 , 500 , NA
                 , 700, NA
                 , 1000, NA
                 # , 1500, NA
                 # , 2000, NA
                 
                , NA, 1
                , NA, 10
                , NA, 100
                , NA, 300
                , NA, 500
                , NA, 700
                , NA, 1000
                # , NA, 1500
                # , NA, 2000

                  )
               , ncol =2, byrow = TRUE)[-(1:2),, drop = F]

ntime <- 10
# Rprof()

benchmarkfile <- file.path(path,paste0("dt_", paste(nCells, sep = "_"), ".rds"))
if(!file.exists(benchmarkfile))
{
   res <- apply(idx, 1, function(r){
              nGeneSampleSize <- r[1]
              nCellSampleSize <- r[2]
              
              if(!is.na(nGeneSampleSize))
                gidx <- sample(nGenes, nGeneSampleSize)
              else
              {
                nGeneSampleSize <- nGenes
                gidx <- NULL
              }
                
              
              if(!is.na(nCellSampleSize))
                cidx <- sample(nCells, nCellSampleSize)
              else
              {
                nCellSampleSize <- nCells
                cidx <- NULL
              }
                
              
              #in memory
              mat_sub <- mat
              if(!is.null(gidx))
                mat_sub <- mat_sub[gidx,]
              if(!is.null(cidx))
                mat_sub <- mat_sub[,cidx]
               timing <- microbenchmark(sub1 <- as.matrix(mat_sub), times = ntime, unit = "ms")
               timing <- summary(timing)[["mean"]]

                dt1 <- data.table(format = paste0("sparse matrix (by cell)")
                                , time = timing)
              
              compress <- "gzip"
              # by cell
              h5array_sub <- h5array_cell
              if(!is.null(gidx))
                h5array_sub <- h5array_sub[gidx,]
              if(!is.null(cidx))
                h5array_sub <- h5array_sub[,cidx]
               timing <- microbenchmark(sub2 <- as.matrix(h5array_sub), times = ntime, unit = "ms")
               timing <- summary(timing)[["mean"]]

                dt2 <- data.table(format = paste0("h5array_by_cell ", compress)
                                , time = timing)

                #h5array_gene
                h5array_sub <- h5array_gene
              if(!is.null(gidx))
                h5array_sub <- h5array_sub[,gidx]
              if(!is.null(cidx))
                h5array_sub <- h5array_sub[cidx,]
               timing <- microbenchmark(sub3 <- as.matrix(h5array_sub), times = ntime, unit = "ms")
               timing <- summary(timing)[["mean"]]

                dt3 <- data.table(format = paste0("h5array_by_gene ", compress)
                                , time = timing)


              #hybrid gzip
              timing <- microbenchmark(sub4 <- h5read.chunked(sc.gz, "data", list(gidx, cidx), block.size = block.size)
                                       , times = ntime, unit = "ms")
              timing <- summary(timing)[["mean"]]
              dt4 <- data.table(format = paste0("hybrid ", compress)
                                , time = timing)
              compress <- "lz4"
              #hybrid lz
              timing <- microbenchmark(sub5 <- h5read.chunked(sc.lz, "data", list(gidx, cidx), block.size = block.size)
                                       , times = ntime, unit = "ms")
              timing <- summary(timing)[["mean"]]
              dt5 <- data.table(format = paste0("hybrid ", compress)
                                , time = timing)


               #h5uncompress
             # h5array <- HDF5Array(h5uncompress, "data")
             # timing <- microbenchmark(dd <- as.matrix(h5array[ridx, ])
             #                           ,dd <-  as.matrix(h5array[, cidx])
             #                           , sub5 <- as.matrix(h5array[ridx, cidx])
             #                           , times = ntime, unit = "ms")
             # timing <- summary(timing)[["mean"]]
             # dt5 <- data.table(format = "h5array (uncompress)"
             #                    , slicing = c("row", "col", "row&col")
             #                    , time = timing)  
              
               H5close()
              
              

              sub3 <- t(sub3)
              if(!isTRUE(all.equal(sub1, sub2, check.attributes = F, tol = 2e-8))||!isTRUE(all.equal(sub1, sub3, check.attributes = F, tol = 2e-8))||!isTRUE(all.equal(sub1, sub4, check.attributes = F, tol = 2e-8))||!isTRUE(all.equal(sub1, sub5, check.attributes = F, tol = 2e-8)))
                stop("wrong reading!")
              thisRes <- rbindlist(list(dt1, dt2, dt3, dt4, dt5))
               # thisRes <- dt4
              thisRes[,nGenes := nGeneSampleSize]
              thisRes[,nCells := nCellSampleSize]
              thisRes
             
            })
  # Rprof(NULL)
  # summaryRprof()
  dt <- rbindlist(res)
  saveRDS(dt, file = benchmarkfile)
}else
  dt <- readRDS(benchmarkfile)
```

## plot the result
```{r fig.width=14}

# dt[, slicing := paste0("nGene=", nGenes, " nCell=", nCells)]
# ggplot(dt, aes(y = time, x = format, fill = format )) + geom_col(position = "dodge")  + ylab("time (ms)")  +facet_wrap(~slicing, scales = "free")
dt[, slicing := ifelse(nGenes == 27998, "nGenes=27998", "nCells=10000")]
dt[, sampleSize := ifelse(nGenes == 27998, nCells, nGenes)]
 ggplot(dt[format!="hybrid lz4",], aes(y = time, x = sampleSize, color = format )) + geom_line() + geom_point()  + ylab("time (ms)")+facet_wrap(~slicing, scales = "free") + scale_y_log10()


```


