# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5createDataset1 <- function(h5file, ds_name, dims, storage_mode, chunk_dims, compressor, nLevel) {
    invisible(.Call('_singleCell_h5createDataset1', PACKAGE = 'singleCell', h5file, ds_name, dims, storage_mode, chunk_dims, compressor, nLevel))
}

h5write1 <- function(data, filename, ds_name, colIndx) {
    .Call('_singleCell_h5write1', PACKAGE = 'singleCell', data, filename, ds_name, colIndx)
}

h5read1 <- function(filename, ds_name, colIndx) {
    .Call('_singleCell_h5read1', PACKAGE = 'singleCell', filename, ds_name, colIndx)
}

h5read2 <- function(filename, ds_name, src_colIndx, mat, dest_colIndx) {
    invisible(.Call('_singleCell_h5read2', PACKAGE = 'singleCell', filename, ds_name, src_colIndx, mat, dest_colIndx))
}

lmdb_open <- function(dbfile) {
    .Call('_singleCell_lmdb_open', PACKAGE = 'singleCell', dbfile)
}

lmdb_close <- function(db) {
    invisible(.Call('_singleCell_lmdb_close', PACKAGE = 'singleCell', db))
}

mdb_insert_cols <- function(db, cidx, vecs) {
    invisible(.Call('_singleCell_mdb_insert_cols', PACKAGE = 'singleCell', db, cidx, vecs))
}

mdb_get_cols <- function(db, cidx) {
    .Call('_singleCell_mdb_get_cols', PACKAGE = 'singleCell', db, cidx)
}

lzcompress <- function(vec, acceleration = 1L, verbose = FALSE) {
    .Call('_singleCell_lzcompress', PACKAGE = 'singleCell', vec, acceleration, verbose)
}

lzdecompress <- function(input, verbose = FALSE) {
    .Call('_singleCell_lzdecompress', PACKAGE = 'singleCell', input, verbose)
}

create_tiledb <- function(dbdir, attr, row_domain, col_domain) {
    invisible(.Call('_singleCell_create_tiledb', PACKAGE = 'singleCell', dbdir, attr, row_domain, col_domain))
}

write_tiledb <- function(dbdir, attr, data, coords) {
    invisible(.Call('_singleCell_write_tiledb', PACKAGE = 'singleCell', dbdir, attr, data, coords))
}

point_selection_tiledb <- function(dbdir, attr, ridx, cidx) {
    .Call('_singleCell_point_selection_tiledb', PACKAGE = 'singleCell', dbdir, attr, ridx, cidx)
}

region_selection_tiledb <- function(dbdir, attr, ridx, cidx) {
    .Call('_singleCell_region_selection_tiledb', PACKAGE = 'singleCell', dbdir, attr, ridx, cidx)
}

