# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5createDataset1 <- function(h5file, ds_name, dims, storage_mode, chunk_dims, compressor, nLevel) {
    invisible(.Call('singleCell_h5createDataset1', PACKAGE = 'singleCell', h5file, ds_name, dims, storage_mode, chunk_dims, compressor, nLevel))
}

h5write1 <- function(data, filename, ds_name, colIndx) {
    .Call('singleCell_h5write1', PACKAGE = 'singleCell', data, filename, ds_name, colIndx)
}

h5read1 <- function(filename, ds_name, colIndx) {
    .Call('singleCell_h5read1', PACKAGE = 'singleCell', filename, ds_name, colIndx)
}

lmdb_open <- function(dbfile) {
    .Call('singleCell_lmdb_open', PACKAGE = 'singleCell', dbfile)
}

lmdb_close <- function(db) {
    invisible(.Call('singleCell_lmdb_close', PACKAGE = 'singleCell', db))
}

mdb_insert_cols <- function(db, cidx, vecs) {
    invisible(.Call('singleCell_mdb_insert_cols', PACKAGE = 'singleCell', db, cidx, vecs))
}

mdb_get_cols <- function(db, cidx) {
    .Call('singleCell_mdb_get_cols', PACKAGE = 'singleCell', db, cidx)
}

lzcompress <- function(vec, acceleration = 1L, verbose = FALSE) {
    .Call('singleCell_lzcompress', PACKAGE = 'singleCell', vec, acceleration, verbose)
}

lzdecompress <- function(input, verbose = FALSE) {
    .Call('singleCell_lzdecompress', PACKAGE = 'singleCell', input, verbose)
}

