# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h5createDataset1 <- function(h5file, ds_name, dims, storage_mode, chunk_dims, compressor, nLevel) {
    invisible(.Call('_singleCell_h5createDataset1', PACKAGE = 'singleCell', h5file, ds_name, dims, storage_mode, chunk_dims, compressor, nLevel))
}

h5write1 <- function(data, filename, ds_name, colIndx) {
    .Call('_singleCell_h5write1', PACKAGE = 'singleCell', data, filename, ds_name, colIndx)
}

h5read1 <- function(filename, ds_name, colIndx) {
    .Call('_singleCell_h5read1', PACKAGE = 'singleCell', filename, ds_name, colIndx)
}

h5read2 <- function(filename, ds_name, src_colIndx, mat, dest_colIndx) {
    invisible(.Call('_singleCell_h5read2', PACKAGE = 'singleCell', filename, ds_name, src_colIndx, mat, dest_colIndx))
}

create_tiledb <- function(dbdir, attr, row_domain, col_domain, tile_extend, isSparse = FALSE) {
    invisible(.Call('_singleCell_create_tiledb', PACKAGE = 'singleCell', dbdir, attr, row_domain, col_domain, tile_extend, isSparse))
}

region_selection_tiledb <- function(dbdir, attr, ridx, cidx, ctx) {
    .Call('_singleCell_region_selection_tiledb', PACKAGE = 'singleCell', dbdir, attr, ridx, cidx, ctx)
}

region_selection_tiledb_sparse <- function(dbdir, attr, ridx, cidx, ctx) {
    .Call('_singleCell_region_selection_tiledb_sparse', PACKAGE = 'singleCell', dbdir, attr, ridx, cidx, ctx)
}

tiledb_query <- function(ctx, uri, type) {
    .Call('_singleCell_tiledb_query', PACKAGE = 'singleCell', ctx, uri, type)
}

tiledb_query_set_coordinates <- function(query, coords) {
    invisible(.Call('_singleCell_tiledb_query_set_coordinates', PACKAGE = 'singleCell', query, coords))
}

tiledb_query_finalize <- function(query) {
    invisible(.Call('_singleCell_tiledb_query_finalize', PACKAGE = 'singleCell', query))
}

tiledb_dim <- function(dbdir) {
    .Call('_singleCell_tiledb_dim', PACKAGE = 'singleCell', dbdir)
}

